config/routes.rb
Imagez::Application.routes.draw do
  resources :videos

  resources :sounds

  resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image_file, ImageUploader
end
 

app/models/sound.rb
class Sound < ActiveRecord::Base
  mount_uploader :audio, AudioUploader
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :image_file)
    end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: [:show, :edit, :update, :destroy]

  # GET /sounds
  # GET /sounds.json
  def index
    @sounds = Sound.all
  end

  # GET /sounds/1
  # GET /sounds/1.json
  def show
  end

  # GET /sounds/new
  def new
    @sound = Sound.new
  end

  # GET /sounds/1/edit
  def edit
  end

  # POST /sounds
  # POST /sounds.json
  def create
    @sound = Sound.new(sound_params)

    respond_to do |format|
      if @sound.save
        format.html { redirect_to @sound, notice: 'Sound was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sound }
      else
        format.html { render action: 'new' }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sounds/1
  # PATCH/PUT /sounds/1.json
  def update
    respond_to do |format|
      if @sound.update(sound_params)
        format.html { redirect_to @sound, notice: 'Sound was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sounds/1
  # DELETE /sounds/1.json
  def destroy
    @sound.destroy
    respond_to do |format|
      format.html { redirect_to sounds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sound
      @sound = Sound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sound_params
      params.require(:sound).permit(:name, :audio)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/images/_form.html.erb
<%= form_for(@image, html: {multipart: true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :image_file %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%# @images.each do |image| %>
      <tr>
        <td><%#= image.name %></td>
        <td><%#= image.image_file %></td>
        <td><%#= link_to 'Show', image %></td>
        <td><%#= link_to 'Edit', edit_image_path(image) %></td>
        <td><%#= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table> -->




  <% @images.each do |image| %>
    <div class="image">
      <div class="border"><%= image_tag image.image_file_url(:thumb) %></div>
      <div class="name"><%= image.name %></div>
      <div class="actions">
        <%= link_to 'Show', image %> |
        <%= link_to 'Edit', edit_image_path(image) %> | 
        <%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>

<div class="clear"></div>
<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>

<p>
  <strong>Image:</strong>
  <div ><%= image_tag @image.image_file, class: "show-image" %></div>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imagez</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sounds/_form.html.erb
<%= form_for(@sound) do |f| %>
  <% if @sound.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sound.errors.count, "error") %> prohibited this sound from being saved:</h2>

      <ul>
      <% @sound.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :audio %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sounds/edit.html.erb
<h1>Editing sound</h1>

<%= render 'form' %>

<%= link_to 'Show', @sound %> |
<%= link_to 'Back', sounds_path %>

app/views/sounds/index.html.erb
<h1>Listing sounds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Audio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sounds.each do |sound| %>
      <tr>
        <td><%= sound.name %></td>
        <td>
            <audio controls="controls">
              Your browser does not support the <code>audio</code> element.
              <source src=<%= sound.audio %> type="audio/mp3">
            </audio>
        </td>
        <td><%= link_to 'Show', sound %></td>
        <td><%= link_to 'Edit', edit_sound_path(sound) %></td>
        <td><%= link_to 'Destroy', sound, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sound', new_sound_path %>

app/views/sounds/new.html.erb
<h1>New sound</h1>

<%= render 'form' %>

<%= link_to 'Back', sounds_path %>

app/views/sounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sound.name %>
</p>

<p>
  <strong>Audio:</strong>
  <audio controls="controls">
    Your browser does not support the <code>audio</code> element.
    <source src=<%= @sound.audio %> type="audio/mp3">
  </audio>
  
</p>

<%= link_to 'Edit', edit_sound_path(@sound) %> |
<%= link_to 'Back', sounds_path %>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody> -->
    <% @videos.each do |video| %>
      <div class="image">
        <div class="border"><%= video_tag video.link %></div>
        <div class="name"><%= video.name %></div>
        <div class="actions">
          <%= link_to 'Show', video %> |
          <%= link_to 'Edit', edit_video_path(video) %> | 
          <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>

      <!-- <tr>
        <td><%#= video.name %></td>
        <td><%#= video.link %></td>
        <td><%#= link_to 'Show', video %></td>
        <td><%#= link_to 'Edit', edit_video_path(video) %></td>
        <td><%#= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
    <% end %>
<!--   </tbody>
</table> -->

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<p>
  <strong>Video:</strong>
  <iframe width="560" height="315" src=<%= @video.link %> frameborder="0" allowfullscreen></iframe>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>